plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lenerd46.spotifyplus'
    compileSdk 35

    def keystorePath = System.getenv("SIGNING_KEYSTORE_FILE")

    defaultConfig {
        applicationId "com.lenerd46.spotifyplus"
        minSdk 27
        targetSdk 35
        versionCode 21
        versionName "0.7.7-9.1.88"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (keystorePath != null) {
                storeFile file(keystorePath)
                storePassword System.getenv("SIGNING_STORE_PASSWORD")
                keyAlias System.getenv("SIGNING_KEY_ALIAS")
                keyPassword System.getenv("SIGNING_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            if (keystorePath != null) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'com.faendir.rhino:rhino-android:1.6.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'com.github.pemistahl:lingua:1.2.2'
    implementation 'com.mikhaellopez:circleview:1.4.1'
    implementation 'org.luckypray:dexkit:2.0.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-ui:1.8.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.8.0'
    implementation 'org.jsoup:jsoup:1.21.2'
//    implementation 'io.github.junkfood02.youtubedl-android:library:0.18.1'
//    implementation 'io.github.junkfood02.youtubedl-android:ffmpeg:0.18.1'
}
